<option value="Brasileira">Brasileira</option>
<option value="Naturalizado brasileiro">Naturalizado brasileiro</option>
<option value="Argentina">Argentina</option>
<option value="Boliviana">Boliviana</option>
<option value="Chilena">Chilena</option>
<option value="Paraguaia">Paraguaia</option>
<option value="Uruguaia">Uruguaia</option>
<option value="Alemã">Alemã</option>
<option value="Belga">Belga</option>
<option value="Britânica">Britânica</option>
<option value="Canadense">Canadense</option>
<option value="Espanhola">Espanhola</option>
<option value="Norte americana">Norte americana</option>
<option value="Francesa">Francesa</option>
<option value="Suíça">Suíça</option>
<option value="Italiana">Italiana</option>
<option value="Japonesa">Japonesa</option>
<option value="Chinesa">Chinesa</option>
<option value="Coreana">Coreana</option>
<option value="Portuguesa">Portuguesa</option>
<option value="Outros (América latina)">Outros (América latina)</option>
<option value="Outros (Asiáticos)">Outros (Asiáticos)</option>
<option value="Outros (Indeterminado)">Outros (Indeterminado)</option>
